import type { Metadata } from 'next';
import './globals.css';
import AuthProvider from './components/admin-panel/AuthProvider';
import App from './App';
import { Toaster } from 'react-hot-toast';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <App>{children}</App>
        </AuthProvider>
        <Toaster position='bottom-center'reverseOrder={false} />
      </body>
    </html>
  );
}